broker: 'redis://@localhost:6379/'
default_queue: machinery_tasks

result_backend: 'redis://@localhost:6379'
results_expire_in: 3600000

amqp:
  binding_key: machinery_task
  exchange: machinery_exchange
  exchange_type: direct
  prefetch_count: 3
